on: push
name: Deploy whale
jobs:
  buildWhale:
    name: Build whale
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build whale
      run: docker build -t jeanlaurent/whale .
    - name: Login to Docker Registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login --username jeanlaurent --password-stdin
    - name: Push to Hub
      run: docker push jeanlaurent/whale
    - name: Ping On Slack
      uses: docker://jeanlaurent/slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: slack jeanlaurent/whale pushed to hub via github actions
