name: Deploy whale

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: dockerbuildbot
        password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

    - name: Generate app token
      id: app_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ vars.DOCKER_READ_APP_ID }}
        private_key: ${{ secrets.DOCKER_READ_APP_PRIVATE_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: cloud
        use: true
        install: true
        endpoint: docker/platform-experience
        version: https://github.com/docker/buildx-private.git#cloud
      env:
        GIT_AUTH_TOKEN: ${{ steps.app_token.outputs.token }}
      
    - name: Creating Docker Image Labels
      id: meta
      uses: docker/metadata-action@v4
      with:
         images: |
            docker/jlwhale
         tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'master') }}
            
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          sbom: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    - name: Ping On Slack
      if: github.event_name != 'pull_request'
      uses: docker://jeanlaurent/slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: slack jeanlaurent/whale pushed to hub via github actions from ${{GitHub.ref}}