name: Deploy whale
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1      

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: jeanlaurent
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Creating Docker Image Labels
      id: meta
      uses: docker/metadata-action@v3
      with:
         images: |
            jeanlaurent/whale
         labels: |
            com.atomist.containers.image.dockerfile=Dockerfile
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jeanlaurent/whale
          labels: ${{ steps.meta.outputs.labels }}          

    - name: Ping On Slack
      uses: docker://jeanlaurent/slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: slack jeanlaurent/whale pushed to hub via github actions
