on: push
name: Deploy jshwale
jobs:
  buildJswhale:
    name: Build jswhale
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build jswhale
      uses: actions/docker/cli@76ff57a
      with:
        args: build -t jeanlaurent/jswhale .
    - name: Login to Docker Registry
      uses: actions/docker/login@76ff57a
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Push to Hub
      uses: actions/docker/cli@76ff57a
      with:
        args: push jeanlaurent/jswhale
    - name: Ping On Slack
      uses: docker://jeanlaurent/slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: slack jeanlaurent/jswhale pushed to hub via github actions
